name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Windows disabled until it works
        # os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository and submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -vv

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run simple example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example mxml_to_svg -- sheets/Ode_to_joy_Piano_for_kids.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check the format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install cargo deny
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deny

      - name: Check licens, duplicates, security issues, bans
        uses: actions-rs/cargo@v1
        with:
          command: deny
          args: check
